[package]
name = "catcat"
version = "0.1.0"
authors = ["lyra"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_size = "0.1.15"
console = "0.13.0"